package view;
import javax.swing.JFrame;
public class virtualdriver{
	public static void main(String[] args){
		JFrame f = new JFrame("Virtual Dance");
		Virtual world = new Virtual("coords.txt");
		f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		f.setSize(700, 700);
		f.setVisible(true);
		f.add(world);
		for (int i = 0; i < args.length; i++)
		{
			String temp = "";
			temp = args[i];
			temp = temp.trim();
		  if (temp.equals("go_forward"))
		  {
			System.out.println("sanity check");
		    world.forward();
		  }
		  else if (args[i].equals("go_backward"))
		    world.backward();
		  else if (args[i].equals("rotate_right"))
		    world.rotate_right();
		  else if (args[i].equals("rotate_left"))
		    world.rotate_left();
		}
		world.forward();
		world.rotate_left();
		world.rotate_right();
		world.backward();
		world.rotate_right();
		world.rotate_right();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.rotate_right();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		//world.forward();
		/*world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.rotate_left();
		world.rotate_left();
		world.rotate_left();
		world.rotate_left();
		world.rotate_left();
		world.rotate_left();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		world.forward();
		*/
	}
}
